# Generated by Django 5.0.6 on 2024-05-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_comment_userprofile_delete_moviedownloadlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
